//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowserPicker.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowserPicker.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Expand file:// urls 的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserBoxExpandUrls {
            get {
                return ResourceManager.GetString("BoxAddBrowserBoxExpandUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserCommand {
            get {
                return ResourceManager.GetString("BoxAddBrowserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command Args:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserCommandArgs {
            get {
                return ResourceManager.GetString("BoxAddBrowserCommandArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable automatic updates 的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserDisableUpdates {
            get {
                return ResourceManager.GetString("BoxAddBrowserDisableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserHotkey {
            get {
                return ResourceManager.GetString("BoxAddBrowserHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Automatic) 的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserHotkeyTip {
            get {
                return ResourceManager.GetString("BoxAddBrowserHotkeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserIcon {
            get {
                return ResourceManager.GetString("BoxAddBrowserIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserName {
            get {
                return ResourceManager.GetString("BoxAddBrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Args:  的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserPrivacyArgs {
            get {
                return ResourceManager.GetString("BoxAddBrowserPrivacyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse file locations 的本地化字符串。
        /// </summary>
        public static string BoxAddBrowserTipBrowseLocations {
            get {
                return ResourceManager.GetString("BoxAddBrowserTipBrowseLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to clipboard 的本地化字符串。
        /// </summary>
        public static string BoxCrashedClipboard {
            get {
                return ResourceManager.GetString("BoxCrashedClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfortunately, BrowserPicker has crashed. 的本地化字符串。
        /// </summary>
        public static string BoxCrashedText1 {
            get {
                return ResourceManager.GetString("BoxCrashedText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please submit a bug report on https://github.com/mortenn/BrowserPicker. 的本地化字符串。
        /// </summary>
        public static string BoxCrashedText2 {
            get {
                return ResourceManager.GetString("BoxCrashedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception details: 的本地化字符串。
        /// </summary>
        public static string BoxCrashedTextInfo {
            get {
                return ResourceManager.GetString("BoxCrashedTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanning URL... 的本地化字符串。
        /// </summary>
        public static string BoxLoadingScanningURL {
            get {
                return ResourceManager.GetString("BoxLoadingScanningURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always ask 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserBoxAlwaysAsk {
            get {
                return ResourceManager.GetString("BoxOpenBrowserBoxAlwaysAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember my choice for 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserBoxRememberChoice {
            get {
                return ResourceManager.GetString("BoxOpenBrowserBoxRememberChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure browser list 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserBtnConfigure {
            get {
                return ResourceManager.GetString("BoxOpenBrowserBtnConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirected URL 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserRedirectedUrl {
            get {
                return ResourceManager.GetString("BoxOpenBrowserRedirectedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the URL to the clipboard 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserTipCopyUrl {
            get {
                return ResourceManager.GetString("BoxOpenBrowserTipCopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit the URL before opening it 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserTipEditUrl {
            get {
                return ResourceManager.GetString("BoxOpenBrowserTipEditUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pins the window, making it not close on lost focus 的本地化字符串。
        /// </summary>
        public static string BoxOpenBrowserTipPin {
            get {
                return ResourceManager.GetString("BoxOpenBrowserTipPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission prompt 的本地化字符串。
        /// </summary>
        public static string CsConfigAdminTip {
            get {
                return ResourceManager.GetString("CsConfigAdminTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal user permission restricted: {0}
        ///Please turn off the security software and try again (no admin required) 的本地化字符串。
        /// </summary>
        public static string CsConfigAdminTipText {
            get {
                return ResourceManager.GetString("CsConfigAdminTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get application filename 的本地化字符串。
        /// </summary>
        public static string CsConfigConfigurationNameErorr {
            get {
                return ResourceManager.GetString("CsConfigConfigurationNameErorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web link selector 的本地化字符串。
        /// </summary>
        public static string CsConfigDefaultProgramRegistration {
            get {
                return ResourceManager.GetString("CsConfigDefaultProgramRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension or ProgID cannot be empty 的本地化字符串。
        /// </summary>
        public static string CsConfigFileTypeRegistration {
            get {
                return ResourceManager.GetString("CsConfigFileTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open{0}file 的本地化字符串。
        /// </summary>
        public static string CsConfigFileTypeRegistrationSuccessful {
            get {
                return ResourceManager.GetString("CsConfigFileTypeRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open link 的本地化字符串。
        /// </summary>
        public static string CsConfigHyperlinkError {
            get {
                return ResourceManager.GetString("CsConfigHyperlinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application needs to restart to apply the new language settings. 的本地化字符串。
        /// </summary>
        public static string CsConfigLanguageChangeRestartMessage {
            get {
                return ResourceManager.GetString("CsConfigLanguageChangeRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open with {0} 的本地化字符串。
        /// </summary>
        public static string CsConfigProgramRegistrationOpen {
            get {
                return ResourceManager.GetString("CsConfigProgramRegistrationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open{0}link with{1} 的本地化字符串。
        /// </summary>
        public static string CsConfigProgramRegistrationOpen2 {
            get {
                return ResourceManager.GetString("CsConfigProgramRegistrationOpen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration failed: {0}
        ///Please check if the app is blocked by security software 的本地化字符串。
        /// </summary>
        public static string CsConfigRegistrationFailed {
            get {
                return ResourceManager.GetString("CsConfigRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration successful!
        ///1. Create a→ new desktop→ shortcut→ Enter the URL→ Right-click to→ open the method→ Select another app→ Find this program
        ///2. Right click any .html file→ Choose another app→ More apps→ Find this program
        ///3. If it is not displayed, it will take effect automatically after restarting the computer 的本地化字符串。
        /// </summary>
        public static string CsConfigRegistrationSuccessful {
            get {
                return ResourceManager.GetString("CsConfigRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to restart the explorer, it is recommended to restart the computer to take effect 的本地化字符串。
        /// </summary>
        public static string CsConfigRestartExplorerFailTip {
            get {
                return ResourceManager.GetString("CsConfigRestartExplorerFailTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to restart Explorer for immediate effect?
        ///The desktop icon will disappear temporarily during the restart process and resume automatically after a few seconds. 的本地化字符串。
        /// </summary>
        public static string CsConfigRestartExplorerTip {
            get {
                return ResourceManager.GetString("CsConfigRestartExplorerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove failure: 的本地化字符串。
        /// </summary>
        public static string CsConfigUnregisterFailed {
            get {
                return ResourceManager.GetString("CsConfigUnregisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully removed all open method associations! 的本地化字符串。
        /// </summary>
        public static string CsConfigUnregisterSuccessful {
            get {
                return ResourceManager.GetString("CsConfigUnregisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove all open method associations?
        ///Once removed, it will not be possible to quickly open the webpage through this program. 的本地化字符串。
        /// </summary>
        public static string CsConfigUnregisterTip {
            get {
                return ResourceManager.GetString("CsConfigUnregisterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export BrowserPicker settings 的本地化字符串。
        /// </summary>
        public static string NameBackupBtnExport {
            get {
                return ResourceManager.GetString("NameBackupBtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import BrowserPicker settings 的本地化字符串。
        /// </summary>
        public static string NameBackupBtnImport {
            get {
                return ResourceManager.GetString("NameBackupBtnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back up or restore your BrowserPicker configuration: 的本地化字符串。
        /// </summary>
        public static string NameBackupText {
            get {
                return ResourceManager.GetString("NameBackupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add browser 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnAddBrowser {
            get {
                return ResourceManager.GetString("NameBrowsersBtnAddBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnDisabled {
            get {
                return ResourceManager.GetString("NameBrowsersBtnDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnEdit {
            get {
                return ResourceManager.GetString("NameBrowsersBtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit browser definition 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnEditTip {
            get {
                return ResourceManager.GetString("NameBrowsersBtnEditTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnEnabled {
            get {
                return ResourceManager.GetString("NameBrowsersBtnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh browser list 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnRefreshBrowserList {
            get {
                return ResourceManager.GetString("NameBrowsersBtnRefreshBrowserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnRemove {
            get {
                return ResourceManager.GetString("NameBrowsersBtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove browser from list 的本地化字符串。
        /// </summary>
        public static string NameBrowsersBtnRemoveTip {
            get {
                return ResourceManager.GetString("NameBrowsersBtnRemoveTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        public static string NameDefaultsMatchHeaderBrowser {
            get {
                return ResourceManager.GetString("NameDefaultsMatchHeaderBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match by 的本地化字符串。
        /// </summary>
        public static string NameDefaultsMatchHeaderMatch {
            get {
                return ResourceManager.GetString("NameDefaultsMatchHeaderMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern 的本地化字符串。
        /// </summary>
        public static string NameDefaultsMatchHeaderPattern {
            get {
                return ResourceManager.GetString("NameDefaultsMatchHeaderPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set default browser per domain 的本地化字符串。
        /// </summary>
        public static string NameDefaultsMatchTextSetDefaultBrowser {
            get {
                return ResourceManager.GetString("NameDefaultsMatchTextSetDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always show browser selection window 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxAlwaysShow {
            get {
                return ResourceManager.GetString("NameSettingBoxAlwaysShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When no default is configured matching the url, use: 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxDefaultMatching {
            get {
                return ResourceManager.GetString("NameSettingBoxDefaultMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use defaults even when browser is not running 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxDefaultsNotRunning {
            get {
                return ResourceManager.GetString("NameSettingBoxDefaultsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disallow network activity 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxDisallowNetworkActivity {
            get {
                return ResourceManager.GetString("NameSettingBoxDisallowNetworkActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always ask when no default is matching url 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxNoDefaultMatching {
            get {
                return ResourceManager.GetString("NameSettingBoxNoDefaultMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off transparency 的本地化字符串。
        /// </summary>
        public static string NameSettingBoxTransparency {
            get {
                return ResourceManager.GetString("NameSettingBoxTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set default browser 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnDefaultBrowser {
            get {
                return ResourceManager.GetString("NameSettingBtnDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register the open method 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnRegAddOpen {
            get {
                return ResourceManager.GetString("NameSettingBtnRegAddOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the open method 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnRegRemoveOpen {
            get {
                return ResourceManager.GetString("NameSettingBtnRegRemoveOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort list alphabetically 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnSortAlphabetically {
            get {
                return ResourceManager.GetString("NameSettingBtnSortAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort list manually 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnSortManually {
            get {
                return ResourceManager.GetString("NameSettingBtnSortManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort list based on usage 的本地化字符串。
        /// </summary>
        public static string NameSettingBtnSortUsage {
            get {
                return ResourceManager.GetString("NameSettingBtnSortUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL resolution timeout: 的本地化字符串。
        /// </summary>
        public static string NameSettingTextBoxUrlResolutionTimeout {
            get {
                return ResourceManager.GetString("NameSettingTextBoxUrlResolutionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actual browser choice: 的本地化字符串。
        /// </summary>
        public static string NameTestDefaultsTextActualChoice {
            get {
                return ResourceManager.GetString("NameTestDefaultsTextActualChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default browser matched: 的本地化字符串。
        /// </summary>
        public static string NameTestDefaultsTextDefaultMatched {
            get {
                return ResourceManager.GetString("NameTestDefaultsTextDefaultMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url: 的本地化字符串。
        /// </summary>
        public static string NameTestDefaultsTextUri {
            get {
                return ResourceManager.GetString("NameTestDefaultsTextUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional shorteners 的本地化字符串。
        /// </summary>
        public static string NameUrlShortenersHeaderAdditional {
            get {
                return ResourceManager.GetString("NameUrlShortenersHeaderAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default shorteners 的本地化字符串。
        /// </summary>
        public static string NameUrlShortenersHeaderDefault {
            get {
                return ResourceManager.GetString("NameUrlShortenersHeaderDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ℹ️ Some additional jump pages not shown above 的本地化字符串。
        /// </summary>
        public static string NameUrlShortenersTextDefault {
            get {
                return ResourceManager.GetString("NameUrlShortenersTextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some pages, such as outlook safelinks, have special handling where the target url is in the query string, these are not listed in this list, as they require additional information in code. 的本地化字符串。
        /// </summary>
        public static string NameUrlShortenersTextTipDefault {
            get {
                return ResourceManager.GetString("NameUrlShortenersTextTipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These domains are known URL shorteners and gets probed on launch unless disallowed by settings 的本地化字符串。
        /// </summary>
        public static string NameUrlShortenersTextTitle {
            get {
                return ResourceManager.GetString("NameUrlShortenersTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to BrowserPicker! 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText1 {
            get {
                return ResourceManager.GetString("NameWelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This message will automatically disappear after 10 seconds 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText10 {
            get {
                return ResourceManager.GetString("NameWelcomeText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Here is the software settings window, 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText2 {
            get {
                return ResourceManager.GetString("NameWelcomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software can select a customized browser when opening a link 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText3 {
            get {
                return ResourceManager.GetString("NameWelcomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you think this software is helpful to you 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText4 {
            get {
                return ResourceManager.GetString("NameWelcomeText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to GitHub give a star☆ 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText5 {
            get {
                return ResourceManager.GetString("NameWelcomeText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you encounter software problems or have new ideas, please visit the project to submit an issue! 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText6 {
            get {
                return ResourceManager.GetString("NameWelcomeText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/mortenn/BrowserPicker 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText7 {
            get {
                return ResourceManager.GetString("NameWelcomeText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you want to contribute to i18n, you can star this project and create a Resource.resx resource file in your own language. 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText8 {
            get {
                return ResourceManager.GetString("NameWelcomeText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/XTsat/BrowserPicker_i18n 的本地化字符串。
        /// </summary>
        public static string NameWelcomeText9 {
            get {
                return ResourceManager.GetString("NameWelcomeText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        public static string TopNameBackup {
            get {
                return ResourceManager.GetString("TopNameBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browsers 的本地化字符串。
        /// </summary>
        public static string TopNameBrowsers {
            get {
                return ResourceManager.GetString("TopNameBrowsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Defaults 的本地化字符串。
        /// </summary>
        public static string TopNameDefaultsMatch {
            get {
                return ResourceManager.GetString("TopNameDefaultsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        public static string TopNameDone {
            get {
                return ResourceManager.GetString("TopNameDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string TopNameExit {
            get {
                return ResourceManager.GetString("TopNameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string TopNameLanguage {
            get {
                return ResourceManager.GetString("TopNameLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behaviour 的本地化字符串。
        /// </summary>
        public static string TopNameSetting {
            get {
                return ResourceManager.GetString("TopNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test defaults 的本地化字符串。
        /// </summary>
        public static string TopNameTestDefaults {
            get {
                return ResourceManager.GetString("TopNameTestDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL shorteners 的本地化字符串。
        /// </summary>
        public static string TopNameUrlShorteners {
            get {
                return ResourceManager.GetString("TopNameUrlShorteners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string TopNameWelcome {
            get {
                return ResourceManager.GetString("TopNameWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string UniAdd {
            get {
                return ResourceManager.GetString("UniAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string UniCancel {
            get {
                return ResourceManager.GetString("UniCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        public static string UniCompleted {
            get {
                return ResourceManager.GetString("UniCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect 的本地化字符串。
        /// </summary>
        public static string UniError {
            get {
                return ResourceManager.GetString("UniError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string UniOk {
            get {
                return ResourceManager.GetString("UniOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string UniOpen {
            get {
                return ResourceManager.GetString("UniOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string UniRemove {
            get {
                return ResourceManager.GetString("UniRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart 的本地化字符串。
        /// </summary>
        public static string UniRestart {
            get {
                return ResourceManager.GetString("UniRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompts 的本地化字符串。
        /// </summary>
        public static string UniTip {
            get {
                return ResourceManager.GetString("UniTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Picker 的本地化字符串。
        /// </summary>
        public static string WindowsTitle {
            get {
                return ResourceManager.GetString("WindowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception has occurred 的本地化字符串。
        /// </summary>
        public static string WindowsTitleCrashed {
            get {
                return ResourceManager.GetString("WindowsTitleCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Browser 的本地化字符串。
        /// </summary>
        public static string WindowsTitleEdit {
            get {
                return ResourceManager.GetString("WindowsTitleEdit", resourceCulture);
            }
        }
    }
}
