name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        version_format: "${major}.${minor}.${patch}"

    outputs:
      version: ${{ steps.version.outputs.version}}
      version_suffix: "beta${{ steps.version.outputs.increment }}"
      package_version: "${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}.${{ steps.version.outputs.increment }}"

  dependent:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    needs: prepare

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build runtime dependent binaries
      uses: "./.github/template/build-signed"
      with:
        base64_encoded_pfx: ${{ secrets.Base64_Encoded_Pfx }}
        pfx_key: ${{ secrets.Pfx_Key }}
        configuration: ${{ matrix.configuration }}
        dotnet_args: "-p VersionPrefix=${{ needs.prepare.outputs.version }} -p VersionSuffix=${{ needs.prepare.outputs.version_suffix }}"
        package_project: dist/Dependent/Dependent.wixproj
        package_version: ${{ needs.prepare.outputs.package_version }}
        package: dist\Dependent\bin\${{ matrix.configuration }}\BrowserPicker.msi
        package_name: DependentSetup-${{ needs.prepare.outputs.version }}-${{ matrix.configuration }}
        package_path: dist/Dependent/bin/${{ matrix.configuration }}
        binaries: |
          src\BrowserPicker.App\bin\${{ matrix.configuration }}\net8.0-windows\publish\BrowserPicker*.dll src\BrowserPicker.App\bin\${{ matrix.configuration }}\net8.0-windows\publish\BrowserPicker*.exe
        bundle_name: Dependent-${{ needs.prepare.outputs.version }}-${{ matrix.configuration }}
        bundle_path: src/BrowserPicker.App/bin/${{ matrix.configuration }}/net8.0-windows/publish

  portable:
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    needs: prepare

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build runtime portable binaries
      uses: "./.github/template/build-signed"
      with:
        base64_encoded_pfx: ${{ secrets.Base64_Encoded_Pfx }}
        pfx_key: ${{ secrets.Pfx_Key }}
        configuration: ${{ matrix.configuration }}
        dotnet_args: "-p VersionPrefix=${{ needs.prepare.outputs.version }} -p VersionSuffix=${{ needs.prepare.outputs.version_suffix }} -r win-x64 -p:PublishSingleFile=true"
        package_project: dist/Portable/Portable.wixproj
        package_version: ${{ needs.prepare.outputs.package_version }}
        package: dist\Portable\bin\${{ matrix.configuration }}\BrowserPicker.msi
        package_name: PortableSetup-${{ needs.prepare.outputs.version }}-${{ matrix.configuration }}
        package_path: dist/Portable/bin/${{ matrix.configuration }}
        binaries: src\BrowserPicker.App\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\publish\BrowserPicker.exe
        bundle_name: Portable-${{ needs.prepare.outputs.version }}-${{ matrix.configuration }}
        bundle_path: src/BrowserPicker.App/bin/${{ matrix.configuration }}/net8.0-windows/win-x64/publish