name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read
    uses: mortenn/BrowserPicker.Actions/.github/workflows/ci.yml@d6c7563889c25c3df4ab20c3535fea675d6e9d12
    with:
      dotnet_version: 10.x
