name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read
    uses: mortenn/BrowserPicker.Actions/.github/workflows/ci.yml@acb9b119377245e0bb213408e8da15f7b0a678b5
    with:
      dotnet_version: 10.x
