name: PR Validation

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  validate:
    permissions:
      contents: read
    uses: mortenn/BrowserPicker.Actions/.github/workflows/pr-validation.yml@1f35242bb89d3bc12c83ca4bd4727f3414204340
    with:
      dotnet_version: 10.x
