name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: mortenn/BrowserPicker.Actions/.github/workflows/release.yml@f8d4053b126ad3f0b3ee6792c5895acaa3b87f04
    with:
      dotnet_version: 10.x
