name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: mortenn/BrowserPicker.Actions/.github/workflows/release.yml@fd5cb1c79ec3a6649a3546b5a983dfc7b75386b8
    with:
      dotnet_version: 10.x
