name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: mortenn/BrowserPicker.Actions/.github/workflows/release.yml@26e97f05ef9173c03ba5ae8eec115d2528aa42d2
    with:
      dotnet_version: 10.x
